# Generated by Django 5.0.2 on 2024-08-28 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cpf', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Novo', 'Novo'), ('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Novo', max_length=20)),
                ('hardware', models.CharField(choices=[('Computador', 'Computador'), ('Impressora', 'Impressora'), ('Celular', 'Celular'), ('Notebook', 'Notebook'), ('Roteador', 'Roteador')], max_length=255)),
                ('servico', models.CharField(choices=[('Formatação', 'Formatação'), ('Troca de placa', 'Troca de placa'), ('Limpeza', 'Limpeza'), ('Atualização de Software', 'Atualização de Software'), ('Remoção de vírus', 'Remoção de vírus')], max_length=255)),
                ('prioridade', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], default='Média', max_length=20)),
                ('descricao', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacao.cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ordens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compartilhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.CharField(choices=[('leitura', 'Somente Leitura'), ('comentario', 'Somente Comentário'), ('editor', 'Editor')], default='leitura', max_length=10)),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos_recebidos', to=settings.AUTH_USER_MODEL)),
                ('usuario_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos_enviados', to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamento', to='Aplicacao.ordem')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacao.ordem')),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacao.ordem')),
            ],
        ),
        migrations.CreateModel(
            name='FavoritasCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacao.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cliente', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='FavoritasOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacao.ordem')),
            ],
            options={
                'unique_together': {('ordem', 'usuario')},
            },
        ),
    ]
